{% set version = "1.8.12" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-psych
  version: {{ version|replace("-", "_") }}

source:
  fn: psych_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/psych_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/psych/psych_{{ version }}.tar.gz
  sha256: 6e175e049bc1ee5b79a9e51ccafb22b962b4e6c839ce5c9cfa1ad83967037743

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-mnormt
    - r-foreign
    - r-lattice
    - r-nlme
  run:
    - r-base
    - r-mnormt
    - r-foreign
    - r-lattice
    - r-nlme

test:
  commands:
    - $R -e "library('psych')"           # [not win]
    - "\"%R%\" -e \"library('psych')\""  # [win]

about:
  home: https://personality-project.org/r/psych https://personality-project.org/r/psych-manual.pdf
  license: GPL (>= 2)
  summary: A general purpose toolbox for personality, psychometric theory and experimental psychology.   Functions
    are primarily for multivariate analysis and scale construction using factor analysis,
    principal component analysis, cluster analysis and reliability analysis, although
    others provide basic descriptive statistics. Item Response Theory is done using  factor
    analysis of tetrachoric and polychoric correlations. Functions for analyzing data
    at multiple levels include within and between group statistics, including correlations
    and factor analysis.   Functions for simulating and testing particular item and
    test structures are included. Several functions  serve as a useful front end for
    structural equation modeling.  Graphical displays of path diagrams, factor analysis
    and structural equation models are created using basic graphics. Some of the functions
    are written to support a book on psychometric theory as well as publications in
    personality research. For more information, see the <https://personality-project.org/r>
    web page.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
